services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    environment:
      - BIND9_USER=root
      - TZ=${TZ}
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ${BIND_VOLUME_CACHE}:/var/cache/bind
      - ${BIND_VOLUME_CONFIG}:/etc/bind
      - ${BIND_VOLUME_RECORDS}:/var/lib/bind
    restart: unless-stopped
