services:
  jellyfin-metadata:
    image: lscr.io/linuxserver/jellyfin:10.9.9
    container_name: jellyfin-metadata
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    volumes:
      - ${JELLYFIN_VOLUME_CONFIG}:/config
      - ${JELLYFIN_VOLUME_MOVIES}:/data/movies
      - ${JELLYFIN_VOLUME_TVSHOWS}:/data/tvshows
      - ${JELLYFIN_VOLUME_SHORTS}:/data/shorts
    restart: unless-stopped
