# More info: https://jellyfin.org/docs/general/administration/hardware-acceleration/intel#configure-with-linux-virtualization
services:
  jellyfin-music:
    image: lscr.io/linuxserver/jellyfin:10.9.9
    container_name: jellyfin-music
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # for hardware-accelerated transcoding (intel quicksync)
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    group_add:
      - "107" # Change this to match your "render" host group id and remove this comment
    ports:
      - 8097:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    # network_mode: host
    volumes:
      - ${JFM_VOLUME_CACHE}:/cache
      - ${JFM_VOLUME_CONFIG}:/config
      - ${JFM_VOLUME_MUSIC}:/data/music
    restart: unless-stopped
