services:
  navidrome:
    image: deluan/navidrome:0.53.3
    container_name: navidrome
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      TZ: ${TZ}
    ports:
      - 4533:4533
    user: ${PUID}:${GUID} # should be owner of volumes
    volumes:
      - navidrome-config:/data
      - navidrome-music:/music:ro
    restart: unless-stopped

include:
  - docker-compose/volume.navidrome.yml
