services:
  navidrome:
    image: deluan/navidrome:0.53.3
    container_name: navidrome
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      TZ: ${TZ}
    ports:
      - 4533:4533
    user: ${PUID}:${GUID} # should be owner of volumes
    volumes:
      - ${NAVIDROME_VOLUME_CONFIG}:/data
      - ${NAVIDROME_VOLUME_MUSIC}:/music:ro
    restart: unless-stopped

version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-stuffhere
    volumes:
      - ./config:/config
      - nfs-video:/media
    restart: unless-stopped  

volumes:
  nfs-video:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.1,nolock,soft,nfsvers=4"
      device: ":/Videos"
