services:
  nginx-proxy-manager:
    image: docker.io/jc21/nginx-proxy-manager:2.11.3
    container_name: nginx-proxy-manager
    cap_add:
      - NET_ADMIN
    environment:
      - DISABLE_IPV6=true
    network_mode: host
#    ports:
#      - 80:80   # Public HTTP Port
#      - 443:443 # Public HTTPS Port
#      - 81:81   # Admin Web Port
#      - 445:445 # samba (truenas)
    volumes:
      - ${NPM_VOLUME_CONFIG}:/data
      - ${NPM_VOLUME_LETSENCRYPT}:/etc/letsencrypt
    restart: unless-stopped
