services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.27.10
    container_name: syncthing
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    hostname: syncthing #optional
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ${SYNCTHING_VOLUME_CONFIG}:/config
      - ${HOST_DATA_1}:${CONTAINER_DATA_1} # avoid having to define shares both in syncthing web gui AND here
      - ${HOST_DATA_2}:${CONTAINER_DATA_2}
      # - ${DATA1_HOST}:${DATA1_CONTAINER}
      # - ${DATA1_HOST}:${DATA1_CONTAINER}
    restart: unless-stopped
